# Generated by Django 4.2.27 on 2026-01-12 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ClientInquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                ("company_name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=30)),
                ("country", models.CharField(max_length=100)),
                (
                    "company_size",
                    models.CharField(
                        choices=[
                            ("1-10", "1-10 employees"),
                            ("11-50", "11-50 employees"),
                            ("51-200", "51-200 employees"),
                            ("201-500", "201-500 employees"),
                            ("500+", "500+ employees"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "industry",
                    models.CharField(
                        choices=[
                            ("healthcare", "Healthcare"),
                            ("finance", "Finance & Banking"),
                            ("ecommerce", "E-Commerce & Retail"),
                            ("education", "Education"),
                            ("real_estate", "Real Estate"),
                            ("logistics", "Logistics & Supply Chain"),
                            ("manufacturing", "Manufacturing"),
                            ("technology", "Technology"),
                            ("media", "Media & Entertainment"),
                            ("government", "Government"),
                            ("nonprofit", "Non-Profit"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("website", models.URLField(blank=True, null=True)),
                (
                    "project_type",
                    models.CharField(
                        choices=[
                            ("mvp", "MVP Development"),
                            ("web_app", "Web Application"),
                            ("mobile_app", "Mobile Application"),
                            ("ai_ml", "AI/ML Solution"),
                            ("digital_transformation", "Digital Transformation"),
                            ("cloud_migration", "Cloud Migration"),
                            ("consulting", "Technical Consulting"),
                            ("maintenance", "Maintenance & Support"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "budget_range",
                    models.CharField(
                        choices=[
                            ("under_10k", "Under $10,000"),
                            ("10k_25k", "$10,000 - $25,000"),
                            ("25k_50k", "$25,000 - $50,000"),
                            ("50k_100k", "$50,000 - $100,000"),
                            ("100k_250k", "$100,000 - $250,000"),
                            ("250k_plus", "$250,000+"),
                            ("undecided", "Not decided yet"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "timeline",
                    models.CharField(
                        choices=[
                            ("asap", "ASAP"),
                            ("1_month", "Within 1 month"),
                            ("1_3_months", "1-3 months"),
                            ("3_6_months", "3-6 months"),
                            ("6_plus_months", "6+ months"),
                            ("flexible", "Flexible"),
                        ],
                        max_length=20,
                    ),
                ),
                ("project_description", models.TextField()),
                ("additional_notes", models.TextField(blank=True, null=True)),
                (
                    "referral_source",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("google", "Google Search"),
                            ("linkedin", "LinkedIn"),
                            ("referral", "Referral"),
                            ("social_media", "Social Media"),
                            ("clutch", "Clutch"),
                            ("event", "Event/Conference"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("in_review", "In Review"),
                            ("contacted", "Contacted"),
                            ("qualified", "Qualified"),
                            ("proposal_sent", "Proposal Sent"),
                            ("negotiating", "Negotiating"),
                            ("won", "Won"),
                            ("lost", "Lost"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                (
                    "assigned_to",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("internal_notes", models.TextField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Client Inquiry",
                "verbose_name_plural": "Client Inquiries",
                "ordering": ["-created_at"],
            },
        ),
    ]
