# Generated by Django 4.2.27 on 2026-01-12 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DeveloperApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=30)),
                ("country", models.CharField(max_length=100)),
                ("years_of_experience", models.PositiveIntegerField()),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("senior_frontend", "Senior Frontend Developer"),
                            ("backend_python", "Backend Developer (Python)"),
                            ("fullstack", "Full Stack Developer"),
                            ("react_native", "React Native Developer"),
                            ("devops", "DevOps Engineer"),
                            ("ml_engineer", "Machine Learning Engineer"),
                            ("qa_engineer", "QA Engineer"),
                            ("ui_ux", "UI/UX Designer"),
                            ("project_manager", "Technical Project Manager"),
                            ("data_engineer", "Data Engineer"),
                            ("security_engineer", "Security Engineer"),
                            ("cloud_architect", "Cloud Solutions Architect"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "work_mode",
                    models.CharField(
                        choices=[
                            ("remote", "Full Remote"),
                            ("hybrid", "Hybrid"),
                            ("onsite", "On-site"),
                        ],
                        max_length=20,
                    ),
                ),
                ("available_from", models.DateField()),
                (
                    "notice_period",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "salary_expectation",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "primary_skills",
                    models.TextField(
                        help_text="Comma-separated list of primary skills"
                    ),
                ),
                (
                    "programming_languages",
                    models.TextField(
                        help_text="Comma-separated list of programming languages"
                    ),
                ),
                (
                    "frameworks",
                    models.TextField(
                        help_text="Comma-separated list of frameworks/tools"
                    ),
                ),
                ("portfolio_url", models.URLField(blank=True, null=True)),
                ("github_url", models.URLField(blank=True, null=True)),
                ("linkedin_url", models.URLField(blank=True, null=True)),
                (
                    "resume",
                    models.FileField(
                        upload_to="resumes/",
                        blank=True,
                        null=True,
                    ),
                ),
                (
                    "english_proficiency",
                    models.CharField(
                        choices=[
                            ("basic", "Basic"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                            ("fluent", "Fluent/Native"),
                        ],
                        default="intermediate",
                        max_length=20,
                    ),
                ),
                ("cover_letter", models.TextField(blank=True, null=True)),
                ("willing_to_relocate", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("submitted", "Submitted"),
                            ("reviewing", "Under Review"),
                            ("screening", "Phone Screening"),
                            ("technical", "Technical Assessment"),
                            ("interview", "Interview Stage"),
                            ("offer", "Offer Extended"),
                            ("hired", "Hired"),
                            ("rejected", "Rejected"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        default="submitted",
                        max_length=20,
                    ),
                ),
                ("screening_notes", models.TextField(blank=True, null=True)),
                ("technical_score", models.PositiveIntegerField(blank=True, null=True)),
                ("interview_notes", models.TextField(blank=True, null=True)),
                (
                    "assigned_to",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Developer Application",
                "verbose_name_plural": "Developer Applications",
                "ordering": ["-created_at"],
            },
        ),
    ]
